### ISSUE TITLE
Error: package com.google.api does not exist

### ISSUE THREAD

**Issue by guerrifrancesco** [wrk-fmd/CoCeCl#12]
I have the following error compiling the app:
error: package com.google.api.client.http does not exist
And the "api" word is highlighted in red, so it means that the problem is with com.google.api. How can I resolve that?

**Comment by robo-w** [comment]
This android client was just a prototype and was never finished. Feel free to play around with the provided code, but sadly the client is not working yet.

we have currently no developer who can offer support for this codebase.
